### ISSUE TITLE
Retail support (again :-) )

### ISSUE THREAD

**Issue by akanouras** [austinrr/details-mirror#3]
The [release.json](https://github.com/austinrr/details-mirror/releases/download/20240503.12699.156/release.json) produced after commit [4250f4d](https://github.com/austinrr/details-mirror/commit/4250f4d4284ac8cd5139623d93df1aa131e43777) is missing `"flavor": "mainline"`, making the retail release uninstallable.

**Comment by austinrr** [comment]
Resolved.

Apparently when the fileId is split causing leading 0s in one of the substrings those 0s need to be truncated before constructing the URL for the GET to the CDN.
